// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"agigame/console/backend/internal/dao/internal"
)

// operLogDao is the data access object for the table sys_oper_log.
// You can define custom methods on it to extend its functionality as needed.
type operLogDao struct {
	*internal.OperLogDao
}

var (
	// OperLog is a globally accessible object for table sys_oper_log operations.
	OperLog = operLogDao{internal.NewOperLogDao()}
)

// Add your custom methods and functionality below.
